version: "3.3"

services:
  game:
      volumes: 
        - ./client:/usr/app
        - /usr/app/node_modules
      build: "./client"
      container_name: "client"
      ports: 
        - "5000:8080"
      command: yarn serve
  # server:
  #   volumes: 
  #     - ./server:/usr/app
  #     - /usr/app/node_modules
  #   build: "./server" 
  #   container_name: "server"
  #   ports:
  #     - "3000:3000"
  #   command: yarn start